### ISSUE TITLE
Install more stuff from specific versions, instead of the git/hg master branch

### ISSUE THREAD

**Issue by fingolfin** [sebasguts/SPPDocker#7]
Installing from git and hg may seem appealing at first, because you automatically get the latest versions like this. But there are several serious drawbacks to this:
- If one uses the same Dockerfile at different points in time, one ends up building different images
- Since code in VCS repos is not always stable (it might not even compile), some of those images may end up broken, containing crashing software etc.
- And even if all master branches were always bug free, software sometimes changes in backwards incompatible ways. So again, you risk ending up with a broken image -- again, even when using the same Dockerfile as before.

At least for flint and normaliz, one could insert fixed versions. Nominally, also for Singular 4.0.2. Probably also for more of the others.

**Comment by sebasguts** [comment]
Done
